#server:
#port: 9000
#spring:
#  datasource:
#    url: jdbc:hsqldb:mem:localhsqldb
#  jpa:
#    hibernate:
#      ddl-auto: none


#spring:
#  datasource:
#    url: jdbc:postgresql://35.189.242.241:5432/foodbookdb
#    username: postgres
#    password: foodbookpassword
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
